### ISSUE TITLE
Differences in reproducing results in the paper

### ISSUE THREAD

**Issue by AlyssaYoung** [Imbalance-VLM/Imbalance-VLM#2]
I have some problems when I try to repoduce the performance of zero-shot CLIP and CLIP+Linear probing. I wonder whether I implement them in the same way with yours. I use the ViT/L-14 backbone and conduct several experiments on the ImageNet-LT dataset. The result is a little bit different from the result in Table 1, I list what I got as follows:
> Zero-shot CLIP 73.57 | 74.56 | 73.15 | 72.26 | 75.27 | 73.57 | 72.92
> CLIP+Linear probing  61.55 | 84.57 | 56.93 | 12.68 | 65.61 | 61.55 | 57.82

For detailed implementation:
CLIP+Linear probing: I slightly modified the setting in imagenet_lt_softmax_None_None_0.yaml, where `freeze_backbone: True decoder_depth: 0`. In this way, the model is just a frozen vision transformer + a classifier, without the decoder layers. Then, I got a lower performance.

Zero-shot CLIP: I individually implement a new class ZeroShotClassifier to build the net as follows:
```
 class ZeroShotClassifier(nn.Module):
    def __init__(self, prompts, model_path):
        super(ZeroShotClassifier, self).__init__()
        self.class_prompts = prompts
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        self.model = CLIPModel.from_pretrained(model_path)
        self.model.to(self.device)
        self.processor = CLIPProcessor.from_pretrained(model_path)

    def forward(self, image):
        image = [img for img in image]
        inputs = self.processor(text=self.class_prompts, images=image, return_tensors="pt", padding=True).to(self.device)
        outputs = self.model(**inputs)
        logits_per_image = outputs.logits_per_image
        probs = logits_per_image.softmax(dim=1)

        return probs
```

Given the class names, the class_prompts are generated by the template "a photo of a {}."  Then I got a higher performance.

Could you help me point out the mistakes or provide a more detailed description about your settings?  Thanks a lot in advance.

**Comment by zhuohaoyu** [comment]
Hi, thank you for your interest in our work.
For zero-shot setting, we implemented zero-shot inference with https://github.com/openai/CLIP.
```python
def classify(dset, idx2label, model, train_label_cnt, many_shot_thr=100, low_shot_thr=20):
    global DEVICE
    res = []
    model = model.to(DEVICE)
    text_features = None
    many_shot_tot = 0
    many_shot_hit = 0
    few_shot_tot = 0
    few_shot_hit = 0
    med_shot_tot = 0
    med_shot_hit = 0
    with torch.no_grad():
        BZ = 256
        for idx in tqdm(range(0, len(idx2label), BZ)):
            inp = clip.tokenize([f"a picture of a {c}" for c in idx2label[idx: idx + BZ]]).to(DEVICE)
            features = model.encode_text(inp)
            if text_features is None:
                text_features = features
            else:
                text_features = torch.cat((text_features, features))
    text_features /= text_features.norm(dim=-1, keepdim=True)
    cnt = 0
    for item in tqdm(dset):
        img, label, path = item
        img = img.to(DEVICE).unsqueeze(0)
        with torch.no_grad():
            image_features = model.encode_image(img)

        image_features /= image_features.norm(dim=-1, keepdim=True)

        similarity = (100.0 * image_features @ text_features.T).softmax(dim=-1)
        values, indices = similarity[0].topk(1)

        for value, index in zip(values, indices):
            pred = index.cpu().numpy()
            if train_label_cnt[label] < low_shot_thr:
                few_shot_tot += 1
                few_shot_hit += pred == label
            elif train_label_cnt[label] > many_shot_hit:
                many_shot_tot += 1
                many_shot_hit += pred == label
            else:
                med_shot_tot += 1
                med_shot_hit += pred == label
            res.append([pred, label])

    res = np.array(res)
    acc = np.mean(np.array(res)[:, 0] == np.array(res)[:, 1])
    y_true = []
    y_pred = []
    for y in res:
        y_true.append(y[1])
        y_pred.append(y[0])

    precision = precision_score(y_true, y_pred, average='macro')
    recall = recall_score(y_true, y_pred, average='macro')
    f1 = f1_score(y_true, y_pred, average='macro')
    return precision, recall, f1, acc, few_shot_hit / few_shot_tot, med_shot_hit / med_shot_tot, many_shot_hit / many_shot_tot
```

For linear probing, our training config file is shown below, the training details can be found on [wandb](https://wandb.ai/imbclip/imagenet_lt/runs/ctoczvgn) and you could also check out our training logs [here](https://archive.org/details/imbalance_lvm_logs_backup).
```yaml
algorithm: supervised
loss_type: softmax
sample_type: None
extra_fc: None
freeze_backbone: False
save_dir: ./saved_models
save_name: inaturalist_fc_0
resume: True
load_path: ./saved_models/inaturalist_fc_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: True
epoch: 32
num_warmup_iter: 512
num_train_iter: 8192
num_eval_iter: 256
num_log_iter: 4
batch_size: 256
eval_batch_size: 256
ema_m: 0.0
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 1.0
net: openai_clip_vit_large_patch14
net_from_name: False
data_dir: /home/yzh/iNaturalist/
dataset: inaturalist
train_sampler: RandomSampler
num_classes: 8142
num_workers: 12
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10005
dist_backend: nccl
gpu: 0
decoder_depth: 0
decoder_mlp_ratio: 0.5
decoder_num_heads: 4

```
